language: java
jdk: oraclejdk8
dist: trusty
install: true
addons:
  sonarcloud:
    organization: "markoniemi-github"
    token: $SONAR_CLOUD_TOKEN
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:report verify sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
after_success:
  - bash <(curl -s https://codecov.io/bash)
